### ISSUE TITLE
Found bugs/issues in README.md and CONTRIBUTING.md

### ISSUE THREAD

**Issue by rishabhbanga** [AMLResearchProject/ALL-Detection-System-2020#18]
**Describe the bug/issue**
-> Unnecessary whitespaces (&nbsp)
-> Information related to Augmentation.py file not present
-> Links to helper files not working because of hhttps in links

**To Reproduce**
NA, except for links which do not appear as links because of extra h

**Expected behavior**
Clean and complete files with any linking errors

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Browser [Chrome]
 - Version [80.0.3987.132 (Official Build)]

**Additional context**

**Comment by rishabhbanga** [comment]
Pull request created - https://github.com/AMLResearchProject/ALL-Detection-System-2020/pulls

**Comment by AdamMiltonBarker** [comment]
Hi Rishabh, thank you for contributing, these would need to be pushed to the current development branch which is 0.0.2.

**Comment by AdamMiltonBarker** [comment]
Automatic close did not work :) Issue is closed with attached pull request. Thank you @rishabhbanga !
